import { writeFile } from 'node:fs/promises';

const homepage = 'https://www.betacalendars.com/';
const months = ['January','February','March','April','May','June','July','August','September','October','November','December'];
const slugs = months.map(x => x.toLowerCase());
const monthRef = i => `https://www.betacalendars.com/${slugs[i]}-calendar.html`;
const commonYear = [{name:'year',in:'path',required:true,schema:{type:'integer',minimum:1,maximum:9999},description:'Gregorian civil year.'}];
const commonMonth = [...commonYear,{name:'month',in:'path',required:true,schema:{type:'integer',minimum:1,maximum:12},description:'Month number, 1 through 12.'}];
const query = (name, description, values, fallback) => ({name,in:'query',required:false,description:`${description}${fallback ? ` Default: ${fallback}.` : ''}`,schema:{type:'string',enum:values,default:fallback}});
const ok = schema => ({'200':{description:'Successful response.',content:{'application/json':{schema}}},'400':{$ref:'#/components/responses/BadRequest'},'404':{$ref:'#/components/responses/NotFound'}});
const monthSchema = {$ref:'#/components/schemas/MonthGrid'};
const paths = {};
function add(path, operation) { paths[path] = {get:operation}; }
function op(summary, description, tags, params=[], schema=monthSchema, externalDocs, examples) {
  const out={summary,description,tags,parameters:params,responses:ok(schema)};
  if(externalDocs) out.externalDocs={description:externalDocs.description,url:externalDocs.url};
  if(examples) out.responses['200'].content['application/json'].examples=examples;
  return out;
}
add('/health',op('Health check','Lightweight readiness endpoint. Returns service name and semantic version only; no environment or deployment details.',['System'],[],{$ref:'#/components/schemas/Health'}));
add('/v1/month/{year}/{month}',op('Generate a month grid','Build a deterministic Gregorian month model with configurable weekday order, natural or fixed six-week rows, adjacent dates, topology, and a month reference.', ['Calendar'],[...commonMonth,query('weekStart','First weekday in the displayed grid.',['sunday','monday','tuesday','wednesday','thursday','friday','saturday'],'monday'),query('gridMode','Choose the minimum natural row count or exactly six rows.',['natural','fixed-six-weeks'],'natural'),query('adjacentDays','Show neighboring dates, leave cells empty, or mark explicit placeholders.',['include','hide','placeholder'],'include')],monthSchema,null,{'january-2027':{summary:'January 2027, Monday-first',value:{year:2027,month:1,monthName:'January',daysInMonth:31,firstWeekday:'friday',lastWeekday:'sunday',weekStart:'monday',gridMode:'natural',rowCount:6,leadingCells:4,trailingCells:7}}}));
add('/v1/print-layout/{year}/{month}',op('Calculate printable page geometry','Calculate physical paper dimensions, margins, header bands, month grid, day-cell dimensions, notes region, and fit warnings in millimeters.', ['Printable Layout'],[...commonMonth,query('paper','ISO or North American paper preset.',['a4','letter','a5','legal'],'a4'),query('orientation','Page orientation.',['portrait','landscape'],'portrait'),{name:'margin',in:'query',description:'Uniform margin in mm (0–50).',schema:{type:'number',minimum:0,maximum:50,default:10}},{name:'headerHeight',in:'query',description:'Reserved title band in mm (0–100).',schema:{type:'number',minimum:0,maximum:100,default:22}},{name:'weekdayHeaderHeight',in:'query',description:'Weekday label band in mm (0–50).',schema:{type:'number',minimum:0,maximum:50,default:10}},{name:'notesHeight',in:'query',description:'Notes band below the calendar in mm (0–150).',schema:{type:'number',minimum:0,maximum:150,default:35}},query('weekStart','First weekday.',['sunday','monday','tuesday','wednesday','thursday','friday','saturday'],'monday'),query('gridMode','Month row policy.',['natural','fixed-six-weeks'],'natural')],{$ref:'#/components/schemas/PrintLayout'}));
add('/v1/blank-calendar',op('Create an undated blank grid','Create a truly undated structural grid and calculate its cell geometry for a supported paper preset. No dates are fabricated.', ['Blank Planning'],[{name:'rows',in:'query',schema:{type:'integer',minimum:1,maximum:12,default:6}},{name:'columns',in:'query',schema:{type:'integer',minimum:1,maximum:12,default:7}},query('paper','Paper preset.',['a4','letter','a5','legal'],'a4'),query('orientation','Page orientation.',['portrait','landscape'],'portrait'),{name:'margin',in:'query',schema:{type:'number',minimum:0,maximum:50,default:10}},{name:'notesHeight',in:'query',schema:{type:'number',minimum:0,maximum:150,default:35}}],{$ref:'#/components/schemas/BlankGrid'},{description:'Blank Calendar Reference',url:'https://www.betacalendars.com/blank-calendar'}));
add('/v1/year/{year}',op('Summarize a Gregorian year','Return leap-year status, total days, and compact summaries for all twelve months.', ['Calendar'],commonYear,{$ref:'#/components/schemas/YearSummary'}));
add('/v1/range',op('Summarize a chronological month range','Return inclusive month summaries in chronological order. Maximum range is 120 months.', ['Ranges'],[{name:'from',in:'query',required:true,schema:{type:'string',pattern:'^\\d{4}-(0[1-9]|1[0-2])$'},example:'2026-11'},{name:'to',in:'query',required:true,schema:{type:'string',pattern:'^\\d{4}-(0[1-9]|1[0-2])$'},example:'2027-02'},query('weekStart','Week layout context to return.',['sunday','monday','tuesday','wednesday','thursday','friday','saturday'],'monday')],{$ref:'#/components/schemas/RangeSummary'}));
add('/v1/topology/{year}/{month}',op('Inspect month grid topology','Return row counts, weekday distribution, leading/trailing positions, weekend count, and a stable topology signature without physical print geometry.', ['Topology'],[...commonMonth,query('weekStart','First weekday.',['sunday','monday','tuesday','wednesday','thursday','friday','saturday'],'monday'),query('gridMode','Row policy.',['natural','fixed-six-weeks'],'natural')],{$ref:'#/components/schemas/Topology'}));
add('/v1/compare',op('Compare selected months','Compare 2–24 month topologies, including year boundaries. Useful for layout selection and regression fixtures.', ['Ranges'],[{name:'months',in:'query',required:true,description:'Comma-separated YYYY-MM values, for example 2026-11,2026-12,2027-01.',schema:{type:'string'},example:'2026-11,2026-12,2027-01,2027-02'}],{$ref:'#/components/schemas/Compare'}));
add('/v1/paper-sizes',op('List paper presets','Return exact dimensions in millimeters for A4, US Letter, A5, and US Legal.', ['Printable Layout'],[],{$ref:'#/components/schemas/PaperSizes'}));
add('/v1/references',op('List human-readable calendar references','Return the project homepage, undated blank-grid page, and one canonical reference URL for each month. These pages accompany the API data.', ['References'],[],{$ref:'#/components/schemas/References'}));
for(let i=0;i<12;i++) add(`/v1/2027/${slugs[i]}`,op(`Generate the 2027 ${months[i]} fixture`,`${months[i]} 2027 is a stable, deterministic fixture for examples and regression testing. It returns the actual calculated month grid and the matching human-readable calendar reference.`,['2027 Month Snapshots'],[query('weekStart','First weekday.',['sunday','monday','tuesday','wednesday','thursday','friday','saturday'],'monday'),query('gridMode','Row policy.',['natural','fixed-six-weeks'],'natural'),query('adjacentDays','Neighboring date presentation.',['include','hide','placeholder'],'include')],monthSchema,{description:`${months[i]} Calendar Reference`,url:monthRef(i)}));

const description='Generate deterministic Gregorian month grids, printable page geometry, undated planning grids, and year/range topology as structured JSON.';
const longDescription=`## BetaCalendars Printable Calendar & Layout\n\nGenerate deterministic Gregorian calendar structures and physical page measurements for applications, print pipelines, planner tools, and regression tests.\n\n### Why this API\n\nThe service models the calendar month first, then derives its week grid and printable geometry. It supports seven week starts, natural or fixed six-week layouts, explicit adjacent-day behavior, A4/US Letter/A5/Legal page presets, and a true blank undated grid. Geometry is returned in millimeters and is calculated without local-time conversions.\n\n### Endpoint families\n\n- **Calendar:** month grids, year summaries, and stable 2027 monthly fixtures.\n- **Printable Layout:** physical paper geometry, margins, headings, weekday bands, writing cells, and notes area.\n- **Blank Planning:** undated grids with configurable rows and columns.\n- **Ranges & Topology:** chronological month ranges, selected-month comparisons, and grid signatures.\n- **References:** human-readable resources accompanying the API.\n\n### Deterministic model\n\nInputs use Gregorian civil year/month values. The service does not scrape holiday/event sources, infer locale-specific holidays, call external URLs, or store user data. Adjacent dates are derived from the same Gregorian model. Invalid input returns a structured JSON error.\n\n### Paper geometry\n\nDimensions are A4 210 × 297 mm, US Letter 215.9 × 279.4 mm, A5 148 × 210 mm, and US Legal 215.9 × 355.6 mm. Orientation swaps width and height. Margins and reserved regions are subtracted before day-cell dimensions are calculated; warnings identify cramped writing areas.\n\n### Example\n\n\`GET /v1/print-layout/2027/1?paper=a4&orientation=portrait&weekStart=monday&gridMode=fixed-six-weeks\`\n\n### Human-readable references\n\nThe API accompanies the [Beta Calendars project](${homepage}) . Printable resources: [Blank Calendar](https://www.betacalendars.com/blank-calendar), [January](https://www.betacalendars.com/january-calendar.html), [February](https://www.betacalendars.com/february-calendar.html), [March](https://www.betacalendars.com/march-calendar.html), [April](https://www.betacalendars.com/april-calendar.html), [May](https://www.betacalendars.com/may-calendar.html), [June](https://www.betacalendars.com/june-calendar.html), [July](https://www.betacalendars.com/july-calendar.html), [August](https://www.betacalendars.com/august-calendar.html), [September](https://www.betacalendars.com/september-calendar.html), [October](https://www.betacalendars.com/october-calendar.html), [November](https://www.betacalendars.com/november-calendar.html), [December](https://www.betacalendars.com/december-calendar.html).`;

const schemas={
  Error:{type:'object',required:['error'],properties:{error:{type:'object',required:['code','message'],properties:{code:{type:'string'},message:{type:'string'}}}}},
  Health:{type:'object',properties:{status:{type:'string',example:'ok'},service:{type:'string',example:'betacalendars-calendar-layout-api'},version:{type:'string',example:'1.0.0'}}},
  MonthGrid:{type:'object',properties:{year:{type:'integer'},month:{type:'integer'},monthName:{type:'string'},daysInMonth:{type:'integer'},firstWeekday:{type:'string'},lastWeekday:{type:'string'},weekStart:{type:'string'},gridMode:{type:'string'},adjacentDays:{type:'string'},rowCount:{type:'integer'},leadingCells:{type:'integer'},trailingCells:{type:'integer'},weeks:{type:'array',items:{type:'array',items:{type:'object',properties:{date:{type:'string',nullable:true},day:{type:'integer',nullable:true},weekday:{type:'string'},inCurrentMonth:{type:'boolean'},isAdjacent:{type:'boolean'},isPlaceholder:{type:'boolean'}}}}},topology:{type:'object'},humanReadableReference:{type:'object',properties:{title:{type:'string'},url:{type:'string',format:'uri'}}}}},
  PrintLayout:{type:'object',properties:{year:{type:'integer'},month:{type:'integer'},paper:{type:'object'},orientation:{type:'string'},printableArea:{type:'object'},header:{type:'object'},weekdayHeader:{type:'object'},calendarGrid:{type:'object'},dayCell:{type:'object'},notesArea:{type:'object'},warnings:{type:'array',items:{type:'string'}}}},
  BlankGrid:{type:'object',properties:{rows:{type:'integer'},columns:{type:'integer'},paper:{type:'object'},orientation:{type:'string'},cellGeometry:{type:'object'},cells:{type:'array',items:{type:'object',properties:{row:{type:'integer'},column:{type:'integer'},label:{type:'string',nullable:true}}}},humanReadableReference:{type:'object'}}},
  MonthSummary:{type:'object',properties:{month:{type:'integer'},monthName:{type:'string'},days:{type:'integer'},firstWeekday:{type:'string'},lastWeekday:{type:'string'},naturalRows:{type:'integer'},fixedRows:{type:'integer'},reference:{type:'string',format:'uri'},weekdayDistribution:{type:'object'},weekendCount:{type:'integer'}}},
  YearSummary:{type:'object',properties:{year:{type:'integer'},leapYear:{type:'boolean'},dayCount:{type:'integer'},months:{type:'array',items:{$ref:'#/components/schemas/MonthSummary'}}}},
  RangeSummary:{type:'object',properties:{from:{type:'string'},to:{type:'string'},weekStart:{type:'string'},count:{type:'integer'},months:{type:'array',items:{$ref:'#/components/schemas/MonthSummary'}}}},
  Topology:{type:'object',properties:{year:{type:'integer'},month:{type:'integer'},monthName:{type:'string'},daysInMonth:{type:'integer'},firstWeekday:{type:'string'},lastWeekday:{type:'string'},weekStart:{type:'string'},gridMode:{type:'string'},leadingCells:{type:'integer'},trailingCells:{type:'integer'},rowCount:{type:'integer'},weekdayDistribution:{type:'object'},weekendCount:{type:'integer'},topologySignature:{type:'string'}}},
  Compare:{type:'object',properties:{months:{type:'array',items:{$ref:'#/components/schemas/MonthSummary'}}}},
  PaperSizes:{type:'object',properties:{papers:{type:'array',items:{type:'object',properties:{id:{type:'string'},name:{type:'string'},widthMm:{type:'number'},heightMm:{type:'number'}}}}}},
  References:{type:'object',properties:{description:{type:'string'},homepage:{type:'object'},blank:{type:'object'},months:{type:'array',items:{type:'object'}}}},
};
const spec={openapi:'3.0.3',info:{title:'BetaCalendars Printable Calendar & Layout',version:'1.0.0',description,'x-category':'Tools','x-long-description':longDescription,'x-website':homepage,'x-public':false,termsOfService:'https://www.betacalendars.com/terms-of-service'},servers:[{url:'https://api.betacalendars.com',description:'Planned production origin; activate after deployment and DNS verification.'}],tags:[{name:'System',description:'Lightweight service status.'},{name:'Calendar',description:'Gregorian month grids and year summaries.'},{name:'Printable Layout',description:'Physical paper presets and print geometry.'},{name:'Blank Planning',description:'Undated configurable planning grids.'},{name:'Ranges',description:'Chronological ranges and selected-month comparisons.'},{name:'Topology',description:'Calendar grid structure and signatures.'},{name:'2027 Month Snapshots',description:'Stable, calculated fixtures for examples and regression testing.'},{name:'References',description:'Human-readable resources accompanying the API.'}],paths,components:{schemas,responses:{BadRequest:{description:'Input failed validation.',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}},NotFound:{description:'No matching API resource exists.',content:{'application/json':{schema:{$ref:'#/components/schemas/Error'}}}}}}};
await writeFile(new URL('../openapi.yaml',import.meta.url),JSON.stringify(spec,null,2)+'\n');
console.log(`Wrote OpenAPI 3.0.3 with ${Object.keys(paths).length} endpoints.`);
